---
- hosts: production
  become: yes
  gather_facts: yes
  vars_files:
    - /ops/config/project.yml
    - /ops/secret_vars/aws/rds.yml
  tasks:

    - name: Ensure db_dumps folder
      file:
        path: /root/db_dumps
        state: directory

    - name: Dump all databases to db_dumps/{{ project_code }}-{{ ansible_date_time.date }}-{{ ansible_date_time.hour }}-{{ ansible_date_time.minute }}.sql
      mysql_db:
        state: dump
        name: "{{ RDS_DB_NAME }}"
        login_host: "{{ RDS_DB_ENDPOINT }}"
        login_user: "{{ RDS_DB_USERNAME }}"
        login_password: "{{ RDS_DB_PASSWORD }}"
        target: "/root/db_dumps/{{ project_code }}-{{ ansible_date_time.date }}-{{ ansible_date_time.hour }}-{{ ansible_date_time.minute }}.sql"

    - name: get dump
      fetch:
        src: "/root/db_dumps/{{ project_code }}-{{ ansible_date_time.date }}-{{ ansible_date_time.hour }}-{{ ansible_date_time.minute }}.sql"
        dest: "/ops/secret_vars/db_dumps/{{ project_code }}-{{ ansible_date_time.date }}-{{ ansible_date_time.hour }}-{{ ansible_date_time.minute }}.sql"
        flat: yes


- hosts: local
  become: yes
  gather_facts: yes
  vars_files:
    - /ops/config/project.yml
    - /ops/secret_vars/aws/rds.yml
  tasks:

    - name: Ensure db_dumps folder
      file:
        path: /ops/secret_vars/db_dumps/
        state: directory

    - name: Restore database
      mysql_db:
        name: "{{ project_code }}"
        state: import
        target: "/ops/secret_vars/db_dumps/{{ project_code }}-{{ ansible_date_time.date }}-{{ ansible_date_time.hour }}-{{ ansible_date_time.minute }}.sql"
